version: "3"
services:
  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "fh-bay"
      MYSQL_PASSWORD: "toor"
      MYSQL_DATABASE: "fh-bay"
      TZ: "Europe/Vienna"